network_path:
  value: donghoon
  dtype: string

model_number:
  value: 50000
  dtype: string

control_dt:
  value: 0.01
  dtype: double

communication_dt_:
  value: 0.00025
  dtype: double

p_gain:
  value: 100.0
  dtype: double

d_gain:
  value: 1.0
  dtype: double

nominal_joint_config_choongin:
  value: [0, 0.56, -1.12, 0, 0.56, -1.12, 0, 0.56, -1.12, 0, 0.56, -1.12]
  dtype: vector

nominal_joint_config_donghoon:
  value: [0, 0.580099, -1.195, 0, 0.580099, -1.195, 0, 0.580099, -1.195, 0, 0.580099, -1.195]
  dtype: vector

plugin:
  iekf: # plugin package name
    rate:
      value: 1000 # loop frequency
      dtype: double
